src/accounts/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.contrib.auth import views as auth_views
from accounts.views import auth as accounts_views
from accounts.views import profile as profile_views

app_name = 'accounts'

urlpatterns = [
    # Accounts connection urls
    url(r'^register/$', accounts_views.UserRegistrationView.as_view(), name='register'),
    url(r'^login/$', accounts_views.UserAuthenticationView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),

    # Accounts reset password urls
    url(r'^reset/$', accounts_views.UserResetPasswordView.as_view(), name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        accounts_views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),

    # Accounts profile urls
    url(r'^profile/$', profile_views.UserProfileView.as_view(), name='profile'),
    url(r'^profile/edit', profile_views.UserProfileEditView.as_view(), name='profile_edit')
]

src/equipments/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from equipments.views.institution import (
    InstitutionListView,
    InstitutionDetailView,
    InstitutionCreateView,
    InstitutionUpdateView,
    InstitutionDeleteView,)

app_name = 'equipments'

urlpatterns = [
    # Intitution views
    url(r'^institutions/$', InstitutionListView.as_view(), name='institution_list'),
    url(r'^institutions/(?P<page>\d+)/$', InstitutionListView.as_view(), name='institution_list'),
    url(r'^institutions/details/(?P<pk>[a-zA-Z0-9]+)/$', InstitutionDetailView.as_view(), name='institution_details'),
    url(r'^institutions/create/$', InstitutionCreateView.as_view(), name='institution_create'),
    url(r'^institutions/update/(?P<pk>[a-zA-Z0-9]+)/$', InstitutionUpdateView.as_view(), name='institution_update'),
    url(r'^institutions/delete/(?P<pk>[a-zA-Z0-9]+)/$', InstitutionDeleteView.as_view(), name='institution_delete'),
]

src/kojump/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.cache import cache_page

from django.views.generic import TemplateView
from core import views as base_views
from equipments.views.activity import ActiveActivityListView, ActivityDetailView, ActivityInstitutionsAPI
from equipments.views.institution import InstitutionPublicDetailView
from searchengine.views import SearchView
from searchengine.services import SearchService
from equipments.services.equipments import InstitutionEquipmentGeoJson


urlpatterns = [

    # base urls
    url(r'^$', ActiveActivityListView.as_view(), name='home'),
    url(r'^(?P<page>\d+)$', ActiveActivityListView.as_view(), name='home'),

    url(r'^activities/(?P<pk>[0-9]+)$', cache_page(60 * 15)(ActivityDetailView.as_view()), name='activity-detail'),
    url(r'^api/activities/(?P<activity_pk>\d+)/institutions/$', cache_page(60 * 15)(ActivityInstitutionsAPI.as_view()),
        name='api.activity.institutions'),

    url(r'^institutions/(?P<pk>[a-zA-Z0-9]+)$', InstitutionPublicDetailView.as_view(), name='institution_details_public'),
    url(r'^api/institutions/(?P<institution_pk>[a-zA-Z0-9]+)/equipments$', InstitutionEquipmentGeoJson.as_view(), name='api.institutions.equipments'),

    url(r'^search/$', cache_page(60 * 15)(SearchView.as_view()), name='search'),
    url(r'^api/search/$', cache_page(60 * 15)(SearchService.as_view()), name='api.search'),

    url(r'^about/$', cache_page(60 * 15)(TemplateView.as_view(template_name='site/about.html')), name='about'),
    url(r'^contact-us/$', cache_page(60 * 15)(base_views.ContactFormView.as_view()), name='contact'),
    url(r'^legal/copyright-policy/',
        cache_page(60 * 15)(TemplateView.as_view(template_name='legal/copyright-policy.html')),
        name='copyright'),
    url(r'^legal/privacy-policy/', cache_page(60 * 15)(TemplateView.as_view(template_name='legal/privacy-policy.html')), name='privacy'),

    # temporary urls
    url(r'^white/$', cache_page(60 * 15)(TemplateView.as_view(template_name='base.html')), name='blank'),
    # admin urls
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^publications/', include('publishing.urls', namespace='publications')),
    url(r'^accounts/equipments/', include('equipments.urls', namespace='equipments')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

src/publishing/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from publishing.views.post import OwnerPostListView

app_name = 'publishing'

urlpatterns = [
    # Included to accounts
    url(r'^accounts/$', OwnerPostListView.as_view(), name='owner_publication'),
]

src/core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _

from slugify import slugify
from django.db import models


class SluggedModel(models.Model):
    label = models.CharField(_('label'), max_length=150)
    slug = models.SlugField(_('slug'), max_length=150)

    def generate_slug(self):
        self.slug = slugify(self.label)

    class Meta:
        abstract = True


class DescribedModel(models.Model):
    description = models.TextField(_('description'))

    class Meta:
        abstract = True


class TimeStampedModel(models.Model):
    created = models.DateTimeField(_('date de création'), auto_now_add=True)
    modified = models.DateTimeField(_('date de modification'), auto_now=True)

    class Meta:
        abstract = True


class ActivatedModel(models.Model):
    is_active = models.BooleanField(_('activer ?'), default=False)

    class Meta:
        abstract = True

src/core/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.core.mail import EmailMessage
from django.template.loader import get_template


class ContactForm(forms.Form):
    name = forms.CharField(label=u'Nom & Prénom', required=True)
    email = forms.EmailField(label=u'Adresse e-mail', required=True)
    subject = forms.CharField(label=u'Le sujet de votre demande', required=True)
    message = forms.CharField(label=u'Votre demande', required=True, widget=forms.Textarea)

    def send_mail(self, recipient_list):

        if not self.is_valid():
            raise ValueError(
                "Cannot generate Context from invalid contact form"
            )

        data = self.cleaned_data
        template = get_template('mails/contact_template.txt')
        context = {
            'name': data['name'],
            'email': data['email'],
            'subject': data['subject'],
            'message': data['message'],
        }
        content = template.render(context)

        email = EmailMessage(
            subject=data['subject'],
            from_email=data['email'],
            to=recipient_list,
            body=content,
            headers={'Reply-To': data['email']}
        )
        email.send(fail_silently=False)

src/core/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import reverse
from django.views.generic.edit import FormView
from django.conf import settings
from core.forms import ContactForm


class ContactFormView(FormView):
    form_class = ContactForm
    recipient_list = settings.DEFAULT_RECIPIENT_LIST
    template_name = 'site/contact-us.html'

    def form_valid(self, form):
        form.send_mail(self.recipient_list)
        return super(ContactFormView, self).form_valid(form)

    def get_success_url(self):
        return reverse('contact')

src/core/templates/parts/footer.html
<footer>
    <div class="uk-container">
        <div class="uk-child-width-1-5@m uk-child-width-1-3@s uk-padding" uk-grid>
            <div><a href="{% url 'privacy' %}">confidentialité & cookies</a></div>
            <div><a href="{% url 'copyright' %}">mentions légales</a></div>
            <div><a href="{% url 'about' %}">à propos</a></div>
            <div><a href="{% url 'contact' %}">nous contacter</a></div>

            <div>
                <a href="" class="uk-icon-button uk-margin-small-right twitter-icon" uk-icon="icon: twitter"></a>
                <a href="" class="uk-icon-button  uk-margin-small-right facebook-icon" uk-icon="icon: facebook"></a>
                <a href="" class="uk-icon-button google-icon" uk-icon="icon: google-plus"></a>
            </div>
        </div>
    </div>
</footer>
<div class="copyright">
    <div class="container">
        <p>&copy; 2017
            <span class="brand"><a target="_blank" href="http://selenkeys.com/" rel="noopener">SELEN KEYS</a></span>
            Tous droits réservés.
        </p>
    </div>
</div>

src/core/templates/parts/menu-elements.html
<li><a href="{% url 'home' %}"><span class="uk-icon uk-margin-small-right" uk-icon="icon: home"></span>Accueil</a></li>
{% if not user.is_authenticated %}
    <li><a href="{% url 'accounts:login' %}?next={{ request.get_full_path|urlencode }}"><span class="uk-icon uk-margin-small-right" uk-icon="icon: sign-in"></span>Se connecter</a></li>
    <li><a href="{% url 'accounts:register' %}"><span class="uk-icon uk-margin-small-right" uk-icon="icon: file-edit"></span>S'inscrire</a></li>
{% else %}
    <li><a href="{% url 'accounts:profile' %}"><span class="uk-icon uk-margin-small-right" uk-icon="icon: info"></span>Mon profil</a></li>
    <!--<li><a href="{% url 'publications:owner_publication' %}"><span class="uk-icon uk-margin-small-right" uk-icon="icon: world"></span>Mes publications</a></li>-->
    <li><a href="{% url 'equipments:institution_list' %}"><span class="uk-icon uk-margin-small-right" uk-icon="icon: world"></span>Mes institutions</a></li>
    <li><a href="{% url 'equipments:institution_create' %}"><span class="uk-icon uk-margin-small-right" uk-icon="icon: plus"></span>Ajouter institution</a></li>
    <li><a href="{% url 'accounts:logout' %}?next={{ request.get_full_path|urlencode }}"><span class="uk-icon uk-margin-small-right" uk-icon="icon: sign-out"></span>Se déconnecter</a></li>
{% endif %}

src/core/templates/parts/navbar.html
{% load static %}
<div uk-sticky="sel-target: .navbar; cls-active: uk-navbar-sticky">
    <nav class="navbar uk-navbar-container uk-box-shadow-medium" uk-navbar>
        <div class="uk-navbar-left">
            <a class="uk-navbar-item uk-logo" href="{% url 'home' %}">
                <img class="uk-margin-small navbar-logo"
                     src="{% static 'img/kojump/kojump_logo.png' %}" alt="KoJump">
            </a>
        </div>
        <div class="uk-navbar-right uk-hidden@s">
            <a class="uk-navbar-toggle" href="#offcanvas-nav" uk-toggle><span uk-navbar-toggle-icon></span></a>
        </div>
        <div class="uk-navbar-right uk-visible@s">
            <ul class="uk-navbar-nav">
                <li class="uk-navbar-item">
                    <input class="uk-input uk-form-width-medium" type="search" id="address-input"
                           placeholder="Rechercher un lieu..."/>
                </li>
                <li class="uk-navbar-item">
                    <a href="#">
                        {% if not user.is_authenticated %}
                            <span class="uk-icon uk-margin-small-right" uk-icon="icon: user"></span> Mon compte
                        {% else %}
                            <span class="uk-icon uk-margin-small-right" uk-icon="icon: user"></span> {{ user.username }}
                        {% endif %}
                    </a>
                    <div class="uk-navbar-dropdown">
                        <ul class="uk-nav uk-navbar-dropdown-nav">
                            {% include 'parts/menu-elements.html' %}
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    <div id="offcanvas-nav" uk-offcanvas="overlay: true">
        <div class="uk-offcanvas-bar">
            <ul class="uk-nav uk-nav-default">
                <li class="uk-parent"><a href="#">Mon Compte</a>
                    <ul class="uk-nav-sub">
                        {% include 'parts/menu-elements.html' %}
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>

src/core/templates/parts/pagination.html
{% if is_paginated %}
    <div class="text-center">
        <ul class="uk-pagination uk-flex-center" uk-margin>

            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">
                    <span class="uk-icon" uk-icon="icon: triangle-left"></span></a>
                </li>
            {% endif %}

            {% if page_obj.number >= 5 %}
                <li><a href="?page=1">1</a></li>
                <li><span>...</span></li>
            {% elif page_obj.number == 4 %}
                <li><a href="?page=1">1</a></li>
            {% endif %}

            {% if page_obj.number|add:"-2" >= 1 %}
                <li><a href="?page={{ page_obj.number|add:"-2" }}">{{ page_obj.number|add:"-2" }}</a></li>
            {% endif %}

            {% if page_obj.number|add:"-1" >= 1 %}
                <li><a href="?page={{ page_obj.number|add:"-1" }}">{{ page_obj.number|add:"-1" }}</a></li>
            {% endif %}

            <li class="uk-active"><a href="?page={{ page_obj.number }}" style="color: #ff4e00">{{ page_obj.number }}</a></li>

            {% if page_obj.number|add:"1" <= paginator.num_pages %}
                <li><a href="?page={{ page_obj.number|add:"1" }}">{{ page_obj.number|add:"1" }}</a></li>
            {% endif %}

            {% if page_obj.number|add:"2" <= paginator.num_pages %}
                <li><a href="?page={{ page_obj.number|add:"2" }}">{{ page_obj.number|add:"2" }}</a></li>
            {% endif %}

            {% if page_obj.number|add:"2" <= paginator.num_pages|add:"-2" %}
                <li><span>...</span></li>
                <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
            {% elif page_obj.number|add:"1" <= paginator.num_pages|add:"-2" %}
                <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
            {% endif %}

            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">
                    <span class="uk-icon" uk-icon="icon: triangle-right"></span></a></a></li>
            {% endif %}
        </ul>
    </div>
{% endif %}