src/accounts/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.contrib.auth import views as auth_views
from accounts.views import auth as accounts_views
from accounts.views import profile as profile_views

app_name = 'accounts'

urlpatterns = [
    # Accounts connection urls
    url(r'^register/$', accounts_views.UserRegistrationView.as_view(), name='register'),
    url(r'^login/$', accounts_views.UserAuthenticationView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),

    # Accounts reset password urls
    url(r'^reset/$', accounts_views.UserResetPasswordView.as_view(), name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        accounts_views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),

    # Accounts profile urls
    url(r'^profile/$', profile_views.UserProfileView.as_view(), name='profile'),
    url(r'^profile/edit', profile_views.UserProfileEditView.as_view(), name='profile_edit')
]

src/kojump/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.cache import cache_page

from django.views.generic import TemplateView
from core import views as base_views
from equipments.views.activity import ActiveActivityListView, ActivityDetailView, ActivityInstitutionsAPI
from equipments.views.institution import InstitutionPublicDetailView
from searchengine.views import SearchView
from searchengine.services import SearchService
from equipments.services.equipments import InstitutionEquipmentGeoJson


urlpatterns = [

    # base urls
    url(r'^$', ActiveActivityListView.as_view(), name='home'),
    url(r'^(?P<page>\d+)$', ActiveActivityListView.as_view(), name='home'),

    url(r'^activities/(?P<pk>[0-9]+)$', cache_page(60 * 15)(ActivityDetailView.as_view()), name='activity-detail'),
    url(r'^api/activities/(?P<activity_pk>\d+)/institutions/$', cache_page(60 * 15)(ActivityInstitutionsAPI.as_view()),
        name='api.activity.institutions'),

    url(r'^institutions/(?P<pk>[a-zA-Z0-9]+)$', InstitutionPublicDetailView.as_view(), name='institution_details_public'),
    url(r'^api/institutions/(?P<institution_pk>[a-zA-Z0-9]+)/equipments$', InstitutionEquipmentGeoJson.as_view(), name='api.institutions.equipments'),

    url(r'^search/$', cache_page(60 * 15)(SearchView.as_view()), name='search'),
    url(r'^api/search/$', cache_page(60 * 15)(SearchService.as_view()), name='api.search'),

    url(r'^about/$', cache_page(60 * 15)(TemplateView.as_view(template_name='site/about.html')), name='about'),
    url(r'^contact-us/$', cache_page(60 * 15)(base_views.ContactFormView.as_view()), name='contact'),
    url(r'^legal/copyright-policy/',
        cache_page(60 * 15)(TemplateView.as_view(template_name='legal/copyright-policy.html')),
        name='copyright'),
    url(r'^legal/privacy-policy/', cache_page(60 * 15)(TemplateView.as_view(template_name='legal/privacy-policy.html')), name='privacy'),

    # temporary urls
    url(r'^white/$', cache_page(60 * 15)(TemplateView.as_view(template_name='base.html')), name='blank'),
    # admin urls
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^publications/', include('publishing.urls', namespace='publications')),
    url(r'^accounts/equipments/', include('equipments.urls', namespace='equipments')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

src/accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from django.db import models

from django.contrib.auth.models import User

GENDER_CHOICES = (
    ('M', _('homme')),
    ('F', _('femme')),
    ('N', _('non spécifié')),
)


@python_2_unicode_compatible
class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(_(u'téléphone'), max_length=16, blank=True, null=True)
    mobile_number = models.CharField(_(u'mobile'), max_length=16, blank=True, null=True)
    fax_number = models.CharField(_(u'fax'), max_length=16, blank=True, null=True)
    street_address = models.CharField(_(u'adresse postale'), max_length=254, blank=True)
    street_address2 = models.CharField(_(u'adresse postale (complément)'), max_length=254, blank=True)
    postal_code = models.CharField(_(u'code postal'), max_length=10, blank=True)
    city = models.CharField(_(u'ville'), max_length=100, blank=True)
    country = models.CharField(_(u'pays'), max_length=100, blank=True)
    photo = models.ImageField(_(u'image de profil'), upload_to='users/%Y/%m/%d', blank=True)
    birth_date = models.DateField(_(u'date de naissance'), blank=True, null=True)
    gender = models.CharField(_('sexe'), max_length=1, choices=GENDER_CHOICES, default='N')
    bio = models.TextField(_(u'présentation'), max_length=1024, null=True, blank=True)
    email_confirmed = models.BooleanField(_(u'adresse e-mail confirmé ?'), default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'profil utilisateur'
        verbose_name_plural = 'profils utilisateurs'

src/accounts/forms/profile.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django import forms
from django.contrib.auth.forms import UserChangeForm

from django.contrib.auth.models import User
from accounts.models import Profile


class UserForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')


class ProfileForm(forms.ModelForm):

    # birth_date = forms.DateField(label=(_(u'date de naissance')), required=False)
    # phone_number = forms.CharField(label=(_(u'numéro de téléphone')), required=False)

    class Meta:
        model = Profile
        fields = ('phone_number', 'mobile_number', 'fax_number', 'street_address', 'street_address2', 'postal_code',
                  'city', 'country', 'photo', 'birth_date', 'gender', 'bio')

src/accounts/views/profile.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _

from django.shortcuts import reverse, get_object_or_404, redirect, render
from django.contrib import messages

from django.views.generic import TemplateView, DetailView
from accounts.forms.profile import UserForm, ProfileForm
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth.models import User


class UserProfileView(LoginRequiredMixin, DetailView):

    model = User
    template_name = 'profile/profile.html'

    def get_object(self, queryset=None):
        return get_object_or_404(User, pk=self.request.user.pk)

    def get_context_data(self, **kwargs):
        if 'object' not in kwargs:
            kwargs['user_form'] = UserForm(instance=self.get_object())

        return super(UserProfileView, self).get_context_data(**kwargs)


class UserProfileEditView(LoginRequiredMixin, TemplateView):

    template_name = 'profile/profile_edit.html'
    profile_form = ProfileForm
    user_form = UserForm

    def get_user(self):
        user = get_object_or_404(User, pk=self.request.user.pk)
        return user

    def get_context_data(self, **kwargs):
        if 'user_form' not in kwargs:
            kwargs['user_form'] = UserForm(instance=self.get_user())

        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = ProfileForm(instance=self.get_user().profile)
        return super(UserProfileEditView, self).get_context_data(**kwargs)

    def post(self, request):
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, _(u'Votre profil a été mis-à-jour avec succès !'))
            return redirect(self.get_success_url())
        messages.error(request, _(u'Merci de vérifier les informations ci-dessous !'))
        return render(request, self.template_name, {'user_form': user_form, 'profile_form': profile_form})

    @staticmethod
    def get_success_url():
        return reverse('accounts:profile')

src/accounts/templates/accounts/authentication.html
{% extends 'base/form.html' %}

{% block title %}
    S'inscrire
{% endblock %}

{% block mainTitle %}Se connecter{% endblock %}

{% block presentationText %}
    <p class="uk-text-meta uk-margin-remove-top">Bienvenue à votre espace membre</p>
{% endblock %}

{% block cardFooter %}
    <div class="uk-card-footer">
        <a href="{% url 'accounts:password_reset' %}" class="uk-button uk-button-text link">mot de passe oublié ?</a>
    </div>
{% endblock %}

src/accounts/templates/accounts/password_reset.html
{% extends 'base/form.html' %}

{% block title %}Réinitialiser mot de passe{% endblock %}
{% block mainTitle %}Mot de passe oublié{% endblock %}

{% block presentationText %}
    <p class="uk-text-meta uk-margin-remove-top">Un e-mail vous serait envoyé comportant la procédure à suivre</p>
{% endblock %}

src/accounts/templates/accounts/password_reset_complete.html
{% extends 'base/card.html' %}

{% block title %}Réinitialiser mot de passe{% endblock %}
{% block mainTitle %}Réinitiliser votre mot de passe{% endblock %}

{% block card-body-content %}
    <p>Votre mot de passe a été réinitialisé avec success. Vous pouvez maitenant vous connecter</p>
    <a class="uk-button uk-button-default" href="{% url 'accounts:login' %}">Revenir à la page de connection</a>
{% endblock %}

src/accounts/templates/accounts/password_reset_confirm.html
{% extends 'base/card.html' %}
{% load class_tags %}

{% block title %}Réinitialiser mot de passe{% endblock %}
{% block mainTitle %}Réinitiliser votre mot de passe{% endblock %}

{% block card-body-content %}
    {% if validlink %}
    <form class="" role="form" action="" method="post">
        {% csrf_token %}
        {% for field in form %}
            {% for error in field.errors %}
                <p class="uk-text-danger">{{ error }}</p>
            {% endfor %}
            <div class="uk-margin">
            <div class="uk-margin">
                <label class="uk-form-label" for="form-horizontal-text">{{ field.label }}</label>
                <div class="uk-form-controls">
                    {{ field|addClass:"uk-input" }}
                </div>
            </div>
            </div>
            {% if field.help_text %}
                <small>{{ field.help_text|safe }}</small>
            {% endif %}
        {% endfor %}

        <div class="uk-margin-top">
            <input class="uk-button button-orange" type="submit" name="submit" value="valider">
        </div>
    </form>
    {% else %}
        <p class="uk-text-justify uk-text-danger">Il se peut que vous avez clické sur un lien invalide. Merci de bien vouloir recommencer</p>
        <a href="{% url 'accounts:password_reset' %}" class="uk-button uk-button-default">recommencer ?</a>
    {% endif %}
{% endblock %}

src/accounts/templates/accounts/password_reset_done.html
{% extends 'base/card.html' %}

{% block title %}Réinitialiser mot de passe{% endblock %}
{% block mainTitle %}Mot de passe oublié{% endblock %}

{% block card-body-content %}
<p>Un e-mail contenant le lien de réinitialisation vous a été envoyé. Merci de vérifier votre boite de réception.<br>
Si, après quelques minute vous ne le recevez toujours pas, merci de vérifier dans les spams
</p>
{% endblock %}

{% block card-footer %}
    <div class="uk-card-footer">
        <a href="{% url 'accounts:login' %}" class="uk-button uk-button-text link">revenir à la page de connection ?</a>
    </div>
{% endblock %}

src/accounts/templates/accounts/register.html
{% extends 'base/form.html' %}

{% block title %}S'inscrire{% endblock %}
{% block mainTitle %}S'inscrire{% endblock %}

{% block form %}
<div>
    <h4>S'enregistrer via les réseaux sociaux</h4>
    <div class="uk-margin-top">
        <a href="#" class="uk-icon-button uk-margin-small-right twitter-icon" uk-icon="icon: twitter"></a>
        <a href="#" class="uk-icon-button  uk-margin-small-right facebook-icon" uk-icon="icon: facebook"></a>
        <a href="#" class="uk-icon-button google-icon" uk-icon="icon: google-plus"></a>
    </div>
</div>
    <div class="uk-divider-icon"></div>
    <h4>Créer un compte</h4>
    {{ block.super }}
{% endblock %}