src/kojump/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.cache import cache_page

from django.views.generic import TemplateView
from core import views as base_views
from equipments.views.activity import ActiveActivityListView, ActivityDetailView, ActivityInstitutionsAPI
from equipments.views.institution import InstitutionPublicDetailView
from searchengine.views import SearchView
from searchengine.services import SearchService
from equipments.services.equipments import InstitutionEquipmentGeoJson


urlpatterns = [

    # base urls
    url(r'^$', ActiveActivityListView.as_view(), name='home'),
    url(r'^(?P<page>\d+)$', ActiveActivityListView.as_view(), name='home'),

    url(r'^activities/(?P<pk>[0-9]+)$', cache_page(60 * 15)(ActivityDetailView.as_view()), name='activity-detail'),
    url(r'^api/activities/(?P<activity_pk>\d+)/institutions/$', cache_page(60 * 15)(ActivityInstitutionsAPI.as_view()),
        name='api.activity.institutions'),

    url(r'^institutions/(?P<pk>[a-zA-Z0-9]+)$', InstitutionPublicDetailView.as_view(), name='institution_details_public'),
    url(r'^api/institutions/(?P<institution_pk>[a-zA-Z0-9]+)/equipments$', InstitutionEquipmentGeoJson.as_view(), name='api.institutions.equipments'),

    url(r'^search/$', cache_page(60 * 15)(SearchView.as_view()), name='search'),
    url(r'^api/search/$', cache_page(60 * 15)(SearchService.as_view()), name='api.search'),

    url(r'^about/$', cache_page(60 * 15)(TemplateView.as_view(template_name='site/about.html')), name='about'),
    url(r'^contact-us/$', cache_page(60 * 15)(base_views.ContactFormView.as_view()), name='contact'),
    url(r'^legal/copyright-policy/',
        cache_page(60 * 15)(TemplateView.as_view(template_name='legal/copyright-policy.html')),
        name='copyright'),
    url(r'^legal/privacy-policy/', cache_page(60 * 15)(TemplateView.as_view(template_name='legal/privacy-policy.html')), name='privacy'),

    # temporary urls
    url(r'^white/$', cache_page(60 * 15)(TemplateView.as_view(template_name='base.html')), name='blank'),
    # admin urls
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^publications/', include('publishing.urls', namespace='publications')),
    url(r'^accounts/equipments/', include('equipments.urls', namespace='equipments')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

src/core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _

from slugify import slugify
from django.db import models


class SluggedModel(models.Model):
    label = models.CharField(_('label'), max_length=150)
    slug = models.SlugField(_('slug'), max_length=150)

    def generate_slug(self):
        self.slug = slugify(self.label)

    class Meta:
        abstract = True


class DescribedModel(models.Model):
    description = models.TextField(_('description'))

    class Meta:
        abstract = True


class TimeStampedModel(models.Model):
    created = models.DateTimeField(_('date de création'), auto_now_add=True)
    modified = models.DateTimeField(_('date de modification'), auto_now=True)

    class Meta:
        abstract = True


class ActivatedModel(models.Model):
    is_active = models.BooleanField(_('activer ?'), default=False)

    class Meta:
        abstract = True

src/core/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.core.mail import EmailMessage
from django.template.loader import get_template


class ContactForm(forms.Form):
    name = forms.CharField(label=u'Nom & Prénom', required=True)
    email = forms.EmailField(label=u'Adresse e-mail', required=True)
    subject = forms.CharField(label=u'Le sujet de votre demande', required=True)
    message = forms.CharField(label=u'Votre demande', required=True, widget=forms.Textarea)

    def send_mail(self, recipient_list):

        if not self.is_valid():
            raise ValueError(
                "Cannot generate Context from invalid contact form"
            )

        data = self.cleaned_data
        template = get_template('mails/contact_template.txt')
        context = {
            'name': data['name'],
            'email': data['email'],
            'subject': data['subject'],
            'message': data['message'],
        }
        content = template.render(context)

        email = EmailMessage(
            subject=data['subject'],
            from_email=data['email'],
            to=recipient_list,
            body=content,
            headers={'Reply-To': data['email']}
        )
        email.send(fail_silently=False)

src/equipments/forms/activity.py
# -*- coding: utf-8 -*-
from django import forms

from equipments.models.activity import Activity


class MultiSelectActivitiesForm(forms.Form):

    activities = forms.ModelMultipleChoiceField(widget=forms.SelectMultiple(),
                                                queryset=Activity.objects.filter(is_active=True).order_by('label'))


class MultiCheckboxActivitiesForm(forms.Form):

    activities = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple(),
                                                queryset=Activity.objects.filter(is_active=True).order_by('label'))

src/core/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import reverse
from django.views.generic.edit import FormView
from django.conf import settings
from core.forms import ContactForm


class ContactFormView(FormView):
    form_class = ContactForm
    recipient_list = settings.DEFAULT_RECIPIENT_LIST
    template_name = 'site/contact-us.html'

    def form_valid(self, form):
        form.send_mail(self.recipient_list)
        return super(ContactFormView, self).form_valid(form)

    def get_success_url(self):
        return reverse('contact')

src/core/templates/site/about.html
{% extends 'base.html' %}
{% load i18n static %}

{% block title %}
A propos de nous
{% endblock %}

{% block content %}
    <article class="uk-article uk-container uk-margin-top uk-margin-bottom">

    <h1 class="uk-article-title" id="title">A propos de nous</h1>

    <p>Tout a commencé lorseque, fraîchement débarqués dans une ville que nous ne connaissons pas, nous avons décidé de
    chercher un terrain pour faire du basket...<br>
    Ne connaissant personne sur place, notre solution a été de parcourir la ville en mode "satellite" sur Google Earth,
    pour trouver quelque chose qui ressemblait de près ou de loin à un terrain de basket. Après 20 bonnes minutes de
    recherche nous avons enfin trouvé le <b>Graal</b>!<br>
    Malheureusement, il s'est avéré que le terrain était situé sur une propriété privé...</p>
    <p>C'est donc pour faciliter cette démarche que nous avons décidé de créer <b>Kojump</b>, une plateforme permettant
    de trouver <b>facilement</b> un endroit où pratiquer une activité sportive!</p>

    <h2 class="uk-article-title">L'équipe</h2>
    <div class="uk-grid-small uk-child-width-1-4@m uk-child-width-1-2@s" uk-grid>
        <div>
            <div class="uk-card uk-card-default">
                <div class="uk-card-media-top">
                    <img src="{% static 'img/user-placeholder.jpg' %}" alt="">
                </div>
                <div class="uk-card-body">
                    <h3 class="uk-card-title">Geoffrey</h3>
                    <dl>
                        <dt>Sport préféré</dt>
                        <dd>Basketball</dd>
                        <dt>Rôle</dt>
                        <dd>Développeur</dd>
                    </dl>
                </div>
            </div>
        </div>
        <div>
            <div class="uk-card uk-card-default">
                <div class="uk-card-media-top">
                    <img src="{% static 'img/user-placeholder.jpg' %}" alt="">
                </div>
                <div class="uk-card-body">
                    <h3 class="uk-card-title">Tom</h3>
                    <dl>
                        <dt>Sport préféré</dt>
                        <dd>Football</dd>
                        <dt>Rôle</dt>
                        <dd>Commercial</dd>
                    </dl>
                </div>
            </div>
        </div>
        <div>
            <div class="uk-card uk-card-default">
                <div class="uk-card-media-top">
                    <img src="{% static 'img/user-placeholder.jpg' %}" alt="">
                </div>
                <div class="uk-card-body">
                    <h3 class="uk-card-title">Jérémy</h3>
                    <dl>
                        <dt>Sport préféré</dt>
                        <dd>Football</dd>
                        <dt>Rôle</dt>
                        <dd>Commercial</dd>
                    </dl>
                </div>
            </div>
        </div>
        <div>
            <div class="uk-card uk-card-default">
                <div class="uk-card-media-top">
                    <img src="{% static 'img/user-placeholder.jpg' %}" alt="">
                </div>
                <div class="uk-card-body">
                    <h3 class="uk-card-title">Cédric</h3>
                    <dl>
                        <dt>Sport préféré</dt>
                        <dd>Football</dd>
                        <dt>Rôle</dt>
                        <dd>Commercial</dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>

</article>
{% endblock %}

src/core/templates/site/activity-detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ activity.label }}{% endblock %}

{% block styles %}
    {{ block.super }}
    <link href='https://api.mapbox.com/mapbox.js/v3.1.1/mapbox.css' rel='stylesheet' />
    <link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.mapbox.css' rel='stylesheet' />
    <!--[if lt IE 9]>
    <link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.ie.css' rel='stylesheet' />
    <![endif]-->
    <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css' rel='stylesheet'/>
{% endblock %}

{% block content %}
    <header class="uk-background-cover uk-height-medium uk-panel uk-flex uk-flex-center uk-flex-middle details-hero"
            style="background-image: url('{% if activity.image %}{{ activity.image.url }}{% else %}{% static 'img/placeholder@l.png' %}{% endif %}')">
        <div class="uk-overlay uk-light uk-position-bottom uk-container">
            <h1 class="uk-article-title">{{ activity.label }}</h1>
        </div>
    </header>

    <section class="uk-container elements-details">
        <article class="uk-article">
            <h2>Description</h2>
            {% if activity.description %}
                <p class="uk-text-justify">{{ activity.description }}</p>
            {% else %}
                <p>Aucune description...</p>
            {% endif %}

            <h3>Disciplines sportives</h3>

            <div class="uk-margin uk-grid-small uk-child-width-auto uk-grid">
                {% for discipline in activity.sports_disciplines.all %}
                    <label><input class="uk-checkbox" type="checkbox"
                                  value="{{ discipline.pk }}"> {{ discipline.label }}</label>
                {% endfor %}
            </div>
            <!-- Advanced Search -->
            <ul uk-accordion="multiple: true">
                <li>
                    <h3 class="uk-accordion-title">Recherche avancée +</h3>
                    <div class="uk-accordion-content">

                        <div>
                            <h5>Paramètres d'accéssibilité</h5>
                            <div class="uk-margin uk-grid-small uk-child-width-1-3@m uk-child-width-1-2@s uk-grid" uk-grid>
                                <label for="is_public"><input id="is_public" name="is_public" type="checkbox" class="uk-checkbox" /> accès aux publiques ?</label>
                                <label for="is_always_open"><input id="is_always_open" name="is_always_open" type="checkbox" class="uk-checkbox" /> ouvert 7j/7 24h/24 ?</label>
                                <label for="only_season"><input id="only_season" name="only_season" type="checkbox" class="uk-checkbox" /> ouvert seulement dans les saisons ?</label>
                            </div>
                        </div>

                    </div>
                </li>
            </ul>
            <!-- /Advanced Search -->
            <button class="uk-button uk-button-default">Filtrer</button>
        </article>
    </section>

    <div class="black-separator"></div>

    <div class="uk-child-width-1-5 uk-grid-small uk-background-muted" data-sticky-container uk-grid>
        <div class="uk-container uk-width-3-5 map-elements-container" id="map-elements-container">
            <div class="uk-margin-top uk-margin-bottom uk-margin-left">
                <input class="uk-input" type="text" placeholder="filtrer">
            </div>
            <div class="uk-child-width-1-2@m uk-grid-small uk-grid-match map-elements" id="map-elements" uk-grid>
                <!-- -->
                <div class="uk-width-1-1">
                    <p>Merci de patienter</p>
                    <div class="spinner-container uk-background-muted">
                        <a class="infinite-more-link" href="#" style="display: block;"
                           uk-spinner></a>
                    </div>
                </div>
                <!-- -->
            </div>
        </div>
        <div class="uk-width-2-5 map-container sticky-map" id="map-container" data-sticky data-margin-top="80">
            <div id='map'></div>
        </div>
    </div>

    <div id="map-control">
        <a href="#" class="uk-icon-link" uk-icon="icon: chevron-right; ratio: 1.5" id="toggle-elements"></a>
        <a href="#" class="uk-icon-link" uk-icon="icon: chevron-left; ratio: 1.5" id="toggle-map"></a>
    </div>

    <div class="black-separator" id="bottom-scroll-spy"></div>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src='https://api.mapbox.com/mapbox.js/v3.1.1/mapbox.js'></script>
    <script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.min.js'></script>
    <script async src="{% static 'js/map.js' %}"></script>
{% endblock %}

src/core/templates/site/contact-us.html
{% extends 'base/form.html' %}
{% load i18n static class_tags %}

{% block title %}Nous Contacter{% endblock %}
{% block mainTitle %}Nous contacter{% endblock %}

{% block form %}
<form class="" role="form" action="" method="post">
    {% csrf_token %}
    {% for field in form %}
        {% for error in field.errors %}
            <p class="uk-text-danger">{{ error }}</p>
        {% endfor %}
        <div class="uk-margin">
            <label class="uk-form-label" for="form-horizontal-text">{{ field.label }}</label>
            <div class="uk-form-controls">
                {% ifequal field.html_name 'message' %}
                    {{ field|addClass:"uk-textarea" }}
                {% else %}
                    {{ field|addClass:"uk-input" }}
                {% endifequal %}
            </div>
        </div>
        {% if field.help_text %}
            <small>{{ field.help_text|safe }}</small>
        {% endif %}
    {% endfor %}

    <div class="uk-margin-top">
        <input class="uk-button button-orange" type="submit" name="submit" value="valider">
    </div>
</form>
{% endblock %}

src/core/templates/site/home.html
{% extends 'base.html' %}
{% load static class_tags %}

{% block title %}Page d'accueil{% endblock %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.4/dist/css/select2.min.css" rel="stylesheet" />

    <style>
        .select2-container--default .select2-results__option--highlighted[aria-selected] {
            background-color: #ff4e00;
        }
        .select2-selection__rendered {
            padding: 5px !important;
        }
        .select2-selection__choice {
            margin-top: 0 !important;
        }
    </style>
{% endblock %}

{% block content %}
    <!-- hero slider -->
    <header class="hero" id="hero">
        <div class="uk-container-expand">
            <div class="hero-slider">
                <div class="uk-background-cover slide lazy" data-src="{% static 'img/home/basket.png' %}"></div>
                <div class="uk-background-cover slide lazy" data-src="{% static 'img/home/football.png' %}"></div>
                <div class="uk-background-cover slide lazy" data-src="{% static 'img/home/golf.png' %}"></div>
                <div class="uk-background-cover slide lazy" data-src="{% static 'img/home/tennis.png' %}"></div>
                <div class="uk-background-cover slide lazy" data-src="{% static 'img/home/skate.png' %}"></div>
                <div class="uk-background-cover slide lazy" data-src="{% static 'img/home/badminton.png' %}"></div>
            </div>
            <div class="uk-position-absolute hero-text">
                <h1 class="uk-text-center" style="color: #f8f8f8">
                    <i uk-icon="icon: search; ratio: 2"></i> Je cherche un terrain de
                    <span class="txt-rotate"
                          data-period="2000"
                          data-rotate='[ "Basket", "Football", "Golf", "Tennis", "Skate" , "Badminton" ]'></span>
                </h1>
            </div>
            <div class="uk-position-absolute hero-btn uk-container">
                <a href="#activities" class="uk-align-center uk-button uk-width-1-2@s button-orange"
                   uk-scroll="offset:80">
                    <span class="uk-margin-small-right" uk-icon="icon: thumbnails"></span>
                    Afficher toutes les activités
                </a>
            </div>
        </div>
    </header>
    <!-- /hero slider -->
    <div class="black-separator"></div>
    <!-- card view -->
    <div class="card-container uk-background-muted" id="activities">
        <div class="uk-container">
            <div class="card-grid uk-grid-small uk-grid-match uk-child-width-1-2@s uk-child-width-1-3@m uk-child-width-1-5@xl infinite-container"
                 uk-grid>
                <div class="uk-width-1-1">
                    <form method="get" action="{% url 'search' %}">
                        {{ form_activities.activities|addClass:"search-sport-input uk-select" }}
                        <input name="previous" type="text" value="{{ request.path }}" hidden>
                        <div class="uk-margin-top">
                            <button class="uk-button uk-button-secondary search-sport-button">Rechercher</button>
                        </div>
                    </form>
                </div>
                {% for activity in activity_list %}
                    <div class="card-element infinite-item">
                        <div class="uk-card uk-card-default uk-card-hover">
                            <div class="uk-card-media-top">
                                {% if activity.image %}
                                    <img class="lazy" src="{{ activity.image.url }}" alt="{{ activity.slug }}">
                                {% else %}
                                    <img class="lazy" src="{% static 'img/placeholder.png' %}" alt="">
                                {% endif %}
                            </div>
                            <div class="uk-card-body">
                                <h3 class="uk-card-title"><a href="{% url 'activity-detail' activity.pk %}">{{ activity.label }}</a></h3>
                                {% if activity.description %}
                                    <p>{{ activity.description }}</p>
                                {% else %}
                                    <p>aucune description</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <!-- -->
            </div>
        </div>
    </div>
    {% if page_obj.has_next %}
        <a class="infinite-more-link" href="{% url 'home' page_obj.next_page_number %}" style="text-align: center; margin: 20px; display: none;" uk-spinner></a>
    {% endif %}
    <!-- /card view -->
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/npm/waypoints@4.0.1/lib/jquery.waypoints.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/waypoints@4.0.1/lib/shortcuts/infinite.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.4/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/lazyload@2.0.0-beta.2/lazyload.js"></script>
    <script>
        var images = document.querySelectorAll(".lazy");
        var lazy = new lazyload(images);
        $(document).ready(function() {
            var infinite = new Waypoint.Infinite({
                element: $('.infinite-container')[0],
                onBeforePageLoad: function () {
                    $('.infinite-more-link').show();
                },
                onAfterPageLoad: function ($items) {
                    $('.infinite-more-link').hide();
                }
            });
            $('#id_activities').select2();
            lazy.loadImages();
        });
    </script>
{% endblock %}